# Generated by Django 4.2.4 on 2023-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='add_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
