# Generated by Django 4.2.4 on 2023-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0004_alter_tabletask_add_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='stage',
            field=models.CharField(max_length=100, verbose_name='Состояние'),
        ),
    ]
