# Generated by Django 4.2.4 on 2023-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0008_alter_tabletask_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabletask',
            old_name='change_at',
            new_name='created_at',
        ),
    ]
