# Generated by Django 4.2.4 on 2023-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0009_rename_change_at_tabletask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='file_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tabletask',
            name='stage',
            field=models.CharField(default='На выводе', max_length=100, null=True, verbose_name='Состояние'),
        ),
    ]
