# Generated by Django 4.2.4 on 2023-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0010_alter_tabletask_file_name_alter_tabletask_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='add_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время добавления'),
        ),
    ]
