# Generated by Django 4.2.4 on 2023-09-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_politext', '0012_tabletask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletask',
            name='user_ready',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_ready', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabletask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
