# Generated by Django 4.2.4 on 2023-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0002_alter_tabletask_add_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletask',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='ready_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время готовности'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='stage',
            field=models.CharField(default='На выводе', max_length=100, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='tabletask',
            name='add_date_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='tabletask',
            name='file_name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
