# Generated by Django 4.2.4 on 2023-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0003_tabletask_equipment_tabletask_ready_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='add_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время добавления'),
        ),
    ]
