# Generated by Django 4.2.4 on 2023-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_politext', '0005_alter_tabletask_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='stage',
            field=models.CharField(default='На выводе', max_length=100, verbose_name='Состояние'),
        ),
    ]
